#pragma kernel FFTRipple

RWStructuredBuffer<float> Data;
RWStructuredBuffer<float> UpdatedData;

[numthreads(512,1,1)]
void FFTRipple (uint threadId : SV_GroupThreadID, uint groupId : SV_GroupID)
{
    if(groupId != 32) // push one circle
        Data[(groupId+1) * 512 + threadId] = Data[groupId * 512 + threadId];
        
    if(groupId == 0 ) // copy from cpu
        Data[threadId] = UpdatedData[threadId];
}
